# Standard package building Travis-CI setup
language: r
sudo: false
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
  
# Set a default pandoc version
# https://docs.travis-ci.com/user/languages/r/#Pandoc
pandoc_version: 2.2

# Setup PAT Token on TravisCI to commit into the gh-pages branch
  
# Initialize the deployment scripts
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh

# Run the bookdown build process
script:
- travis_wait 45 "./deployment/_build.sh"

# Determine if the build should be propogated out to the website or not.
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash ./deployment/_deploy.sh
